# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/namgihun/gnss_INS_fusion_loosely_ver_1.2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/namgihun/gnss_INS_fusion_loosely_ver_1.2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/namgihun/gnss_INS_fusion_loosely_ver_1.2/CMakeFiles /home/namgihun/gnss_INS_fusion_loosely_ver_1.2/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/namgihun/gnss_INS_fusion_loosely_ver_1.2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named novatel

# Build rule for target.
novatel: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 novatel
.PHONY : novatel

# fast build rule for target.
novatel/fast:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/build
.PHONY : novatel/fast

#=============================================================================
# Target rules for targets named EKFNav

# Build rule for target.
EKFNav: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 EKFNav
.PHONY : EKFNav

# fast build rule for target.
EKFNav/fast:
	$(MAKE) -f CMakeFiles/EKFNav.dir/build.make CMakeFiles/EKFNav.dir/build
.PHONY : EKFNav/fast

src/HgDataParser.o: src/HgDataParser.cpp.o

.PHONY : src/HgDataParser.o

# target to build an object file
src/HgDataParser.cpp.o:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/HgDataParser.cpp.o
.PHONY : src/HgDataParser.cpp.o

src/HgDataParser.i: src/HgDataParser.cpp.i

.PHONY : src/HgDataParser.i

# target to preprocess a source file
src/HgDataParser.cpp.i:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/HgDataParser.cpp.i
.PHONY : src/HgDataParser.cpp.i

src/HgDataParser.s: src/HgDataParser.cpp.s

.PHONY : src/HgDataParser.s

# target to generate assembly for a file
src/HgDataParser.cpp.s:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/HgDataParser.cpp.s
.PHONY : src/HgDataParser.cpp.s

src/LCEKF.o: src/LCEKF.cpp.o

.PHONY : src/LCEKF.o

# target to build an object file
src/LCEKF.cpp.o:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/LCEKF.cpp.o
.PHONY : src/LCEKF.cpp.o

src/LCEKF.i: src/LCEKF.cpp.i

.PHONY : src/LCEKF.i

# target to preprocess a source file
src/LCEKF.cpp.i:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/LCEKF.cpp.i
.PHONY : src/LCEKF.cpp.i

src/LCEKF.s: src/LCEKF.cpp.s

.PHONY : src/LCEKF.s

# target to generate assembly for a file
src/LCEKF.cpp.s:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/LCEKF.cpp.s
.PHONY : src/LCEKF.cpp.s

src/Serial.o: src/Serial.cpp.o

.PHONY : src/Serial.o

# target to build an object file
src/Serial.cpp.o:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/Serial.cpp.o
.PHONY : src/Serial.cpp.o

src/Serial.i: src/Serial.cpp.i

.PHONY : src/Serial.i

# target to preprocess a source file
src/Serial.cpp.i:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/Serial.cpp.i
.PHONY : src/Serial.cpp.i

src/Serial.s: src/Serial.cpp.s

.PHONY : src/Serial.s

# target to generate assembly for a file
src/Serial.cpp.s:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/Serial.cpp.s
.PHONY : src/Serial.cpp.s

src/filter_functions.o: src/filter_functions.cpp.o

.PHONY : src/filter_functions.o

# target to build an object file
src/filter_functions.cpp.o:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/filter_functions.cpp.o
.PHONY : src/filter_functions.cpp.o

src/filter_functions.i: src/filter_functions.cpp.i

.PHONY : src/filter_functions.i

# target to preprocess a source file
src/filter_functions.cpp.i:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/filter_functions.cpp.i
.PHONY : src/filter_functions.cpp.i

src/filter_functions.s: src/filter_functions.cpp.s

.PHONY : src/filter_functions.s

# target to generate assembly for a file
src/filter_functions.cpp.s:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/filter_functions.cpp.s
.PHONY : src/filter_functions.cpp.s

src/main_demoz.o: src/main_demoz.cpp.o

.PHONY : src/main_demoz.o

# target to build an object file
src/main_demoz.cpp.o:
	$(MAKE) -f CMakeFiles/EKFNav.dir/build.make CMakeFiles/EKFNav.dir/src/main_demoz.cpp.o
.PHONY : src/main_demoz.cpp.o

src/main_demoz.i: src/main_demoz.cpp.i

.PHONY : src/main_demoz.i

# target to preprocess a source file
src/main_demoz.cpp.i:
	$(MAKE) -f CMakeFiles/EKFNav.dir/build.make CMakeFiles/EKFNav.dir/src/main_demoz.cpp.i
.PHONY : src/main_demoz.cpp.i

src/main_demoz.s: src/main_demoz.cpp.s

.PHONY : src/main_demoz.s

# target to generate assembly for a file
src/main_demoz.cpp.s:
	$(MAKE) -f CMakeFiles/EKFNav.dir/build.make CMakeFiles/EKFNav.dir/src/main_demoz.cpp.s
.PHONY : src/main_demoz.cpp.s

src/matops.o: src/matops.c.o

.PHONY : src/matops.o

# target to build an object file
src/matops.c.o:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/matops.c.o
.PHONY : src/matops.c.o

src/matops.i: src/matops.c.i

.PHONY : src/matops.i

# target to preprocess a source file
src/matops.c.i:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/matops.c.i
.PHONY : src/matops.c.i

src/matops.s: src/matops.c.s

.PHONY : src/matops.s

# target to generate assembly for a file
src/matops.c.s:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/matops.c.s
.PHONY : src/matops.c.s

src/novatel.o: src/novatel.cpp.o

.PHONY : src/novatel.o

# target to build an object file
src/novatel.cpp.o:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/novatel.cpp.o
.PHONY : src/novatel.cpp.o

src/novatel.i: src/novatel.cpp.i

.PHONY : src/novatel.i

# target to preprocess a source file
src/novatel.cpp.i:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/novatel.cpp.i
.PHONY : src/novatel.cpp.i

src/novatel.s: src/novatel.cpp.s

.PHONY : src/novatel.s

# target to generate assembly for a file
src/novatel.cpp.s:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/novatel.cpp.s
.PHONY : src/novatel.cpp.s

src/signa_core.o: src/signa_core.cpp.o

.PHONY : src/signa_core.o

# target to build an object file
src/signa_core.cpp.o:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/signa_core.cpp.o
.PHONY : src/signa_core.cpp.o

src/signa_core.i: src/signa_core.cpp.i

.PHONY : src/signa_core.i

# target to preprocess a source file
src/signa_core.cpp.i:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/signa_core.cpp.i
.PHONY : src/signa_core.cpp.i

src/signa_core.s: src/signa_core.cpp.s

.PHONY : src/signa_core.s

# target to generate assembly for a file
src/signa_core.cpp.s:
	$(MAKE) -f CMakeFiles/novatel.dir/build.make CMakeFiles/novatel.dir/src/signa_core.cpp.s
.PHONY : src/signa_core.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... novatel"
	@echo "... EKFNav"
	@echo "... src/HgDataParser.o"
	@echo "... src/HgDataParser.i"
	@echo "... src/HgDataParser.s"
	@echo "... src/LCEKF.o"
	@echo "... src/LCEKF.i"
	@echo "... src/LCEKF.s"
	@echo "... src/Serial.o"
	@echo "... src/Serial.i"
	@echo "... src/Serial.s"
	@echo "... src/filter_functions.o"
	@echo "... src/filter_functions.i"
	@echo "... src/filter_functions.s"
	@echo "... src/main_demoz.o"
	@echo "... src/main_demoz.i"
	@echo "... src/main_demoz.s"
	@echo "... src/matops.o"
	@echo "... src/matops.i"
	@echo "... src/matops.s"
	@echo "... src/novatel.o"
	@echo "... src/novatel.i"
	@echo "... src/novatel.s"
	@echo "... src/signa_core.o"
	@echo "... src/signa_core.i"
	@echo "... src/signa_core.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

